/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AttributeDto
 */
@JsonPropertyOrder({
  AttributeDto.JSON_PROPERTY_BOOLEAN_VALUE,
  AttributeDto.JSON_PROPERTY_DOUBLE_VALUE,
  AttributeDto.JSON_PROPERTY_KEY,
  AttributeDto.JSON_PROPERTY_LONG_VALUE,
  AttributeDto.JSON_PROPERTY_OBJECT_VALUE,
  AttributeDto.JSON_PROPERTY_STRING_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-09T10:54:31.162605Z[Etc/UTC]")
public class AttributeDto {
  public static final String JSON_PROPERTY_BOOLEAN_VALUE = "booleanValue";
  private Boolean booleanValue;

  public static final String JSON_PROPERTY_DOUBLE_VALUE = "doubleValue";
  private Double doubleValue;

  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_LONG_VALUE = "longValue";
  private Long longValue;

  public static final String JSON_PROPERTY_OBJECT_VALUE = "objectValue";
  private Object objectValue;

  public static final String JSON_PROPERTY_STRING_VALUE = "stringValue";
  private String stringValue;

  public AttributeDto() {
  }

  public AttributeDto booleanValue(Boolean booleanValue) {
    
    this.booleanValue = booleanValue;
    return this;
  }

   /**
   * Get booleanValue
   * @return booleanValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BOOLEAN_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBooleanValue() {
    return booleanValue;
  }


  @JsonProperty(JSON_PROPERTY_BOOLEAN_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBooleanValue(Boolean booleanValue) {
    this.booleanValue = booleanValue;
  }


  public AttributeDto doubleValue(Double doubleValue) {
    
    this.doubleValue = doubleValue;
    return this;
  }

   /**
   * Get doubleValue
   * @return doubleValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOUBLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDoubleValue() {
    return doubleValue;
  }


  @JsonProperty(JSON_PROPERTY_DOUBLE_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoubleValue(Double doubleValue) {
    this.doubleValue = doubleValue;
  }


  public AttributeDto key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(String key) {
    this.key = key;
  }


  public AttributeDto longValue(Long longValue) {
    
    this.longValue = longValue;
    return this;
  }

   /**
   * Get longValue
   * @return longValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LONG_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLongValue() {
    return longValue;
  }


  @JsonProperty(JSON_PROPERTY_LONG_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongValue(Long longValue) {
    this.longValue = longValue;
  }


  public AttributeDto objectValue(Object objectValue) {
    
    this.objectValue = objectValue;
    return this;
  }

   /**
   * Get objectValue
   * @return objectValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OBJECT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getObjectValue() {
    return objectValue;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjectValue(Object objectValue) {
    this.objectValue = objectValue;
  }


  public AttributeDto stringValue(String stringValue) {
    
    this.stringValue = stringValue;
    return this;
  }

   /**
   * Get stringValue
   * @return stringValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STRING_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStringValue() {
    return stringValue;
  }


  @JsonProperty(JSON_PROPERTY_STRING_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStringValue(String stringValue) {
    this.stringValue = stringValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeDto attributeDto = (AttributeDto) o;
    return Objects.equals(this.booleanValue, attributeDto.booleanValue) &&
        Objects.equals(this.doubleValue, attributeDto.doubleValue) &&
        Objects.equals(this.key, attributeDto.key) &&
        Objects.equals(this.longValue, attributeDto.longValue) &&
        Objects.equals(this.objectValue, attributeDto.objectValue) &&
        Objects.equals(this.stringValue, attributeDto.stringValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(booleanValue, doubleValue, key, longValue, objectValue, stringValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeDto {\n");
    sb.append("    booleanValue: ").append(toIndentedString(booleanValue)).append("\n");
    sb.append("    doubleValue: ").append(toIndentedString(doubleValue)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    longValue: ").append(toIndentedString(longValue)).append("\n");
    sb.append("    objectValue: ").append(toIndentedString(objectValue)).append("\n");
    sb.append("    stringValue: ").append(toIndentedString(stringValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

