/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NetworkMetricDto
 */
@JsonPropertyOrder({
  NetworkMetricDto.JSON_PROPERTY_NETWORK_I_O_RX_MB,
  NetworkMetricDto.JSON_PROPERTY_NETWORK_I_O_TX_MB
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-31T12:24:20.857460Z[Etc/UTC]")
public class NetworkMetricDto {
  public static final String JSON_PROPERTY_NETWORK_I_O_RX_MB = "networkIORxMb";
  private Long networkIORxMb;

  public static final String JSON_PROPERTY_NETWORK_I_O_TX_MB = "networkIOTxMb";
  private Long networkIOTxMb;

  public NetworkMetricDto() {
  }

  public NetworkMetricDto networkIORxMb(Long networkIORxMb) {
    
    this.networkIORxMb = networkIORxMb;
    return this;
  }

   /**
   * Get networkIORxMb
   * @return networkIORxMb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK_I_O_RX_MB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNetworkIORxMb() {
    return networkIORxMb;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_I_O_RX_MB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetworkIORxMb(Long networkIORxMb) {
    this.networkIORxMb = networkIORxMb;
  }


  public NetworkMetricDto networkIOTxMb(Long networkIOTxMb) {
    
    this.networkIOTxMb = networkIOTxMb;
    return this;
  }

   /**
   * Get networkIOTxMb
   * @return networkIOTxMb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK_I_O_TX_MB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNetworkIOTxMb() {
    return networkIOTxMb;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_I_O_TX_MB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetworkIOTxMb(Long networkIOTxMb) {
    this.networkIOTxMb = networkIOTxMb;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkMetricDto networkMetricDto = (NetworkMetricDto) o;
    return Objects.equals(this.networkIORxMb, networkMetricDto.networkIORxMb) &&
        Objects.equals(this.networkIOTxMb, networkMetricDto.networkIOTxMb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkIORxMb, networkIOTxMb);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkMetricDto {\n");
    sb.append("    networkIORxMb: ").append(toIndentedString(networkIORxMb)).append("\n");
    sb.append("    networkIOTxMb: ").append(toIndentedString(networkIOTxMb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

