/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RepoDto
 */
@JsonPropertyOrder({
  RepoDto.JSON_PROPERTY_ACCOUNT_OWNER_USER_ACCOUNT_ID,
  RepoDto.JSON_PROPERTY_CREATED_AT,
  RepoDto.JSON_PROPERTY_DEFAULT_BRANCH,
  RepoDto.JSON_PROPERTY_FULL_NAME,
  RepoDto.JSON_PROPERTY_ID,
  RepoDto.JSON_PROPERTY_NAME,
  RepoDto.JSON_PROPERTY_OWNER,
  RepoDto.JSON_PROPERTY_PROVIDER,
  RepoDto.JSON_PROPERTY_PUBLICLY_ACCESSIBLE,
  RepoDto.JSON_PROPERTY_REPO_INFORMED_STATUS,
  RepoDto.JSON_PROPERTY_USER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-31T12:24:20.857460Z[Etc/UTC]")
public class RepoDto {
  public static final String JSON_PROPERTY_ACCOUNT_OWNER_USER_ACCOUNT_ID = "accountOwnerUserAccountId";
  private String accountOwnerUserAccountId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private Long createdAt;

  public static final String JSON_PROPERTY_DEFAULT_BRANCH = "defaultBranch";
  private String defaultBranch;

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  private String fullName;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_OWNER = "owner";
  private String owner;

  /**
   * Gets or Sets provider
   */
  public enum ProviderEnum {
    GIT("GIT"),
    
    GITHUB("GITHUB"),
    
    GITLAB("GITLAB"),
    
    BITBUCKET("BITBUCKET"),
    
    AZURE("AZURE"),
    
    TRAVISCI("TRAVISCI"),
    
    CIRCLECI("CIRCLECI"),
    
    JENKINS("JENKINS"),
    
    CODEBUILD("CODEBUILD");

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  private ProviderEnum provider;

  public static final String JSON_PROPERTY_PUBLICLY_ACCESSIBLE = "publiclyAccessible";
  private Boolean publiclyAccessible;

  /**
   * Gets or Sets repoInformedStatus
   */
  public enum RepoInformedStatusEnum {
    INITIAL("INITIAL"),
    
    STARTED("STARTED"),
    
    COMPLETED("COMPLETED"),
    
    COMPLETED_WITH_NO_WORKFLOW("COMPLETED_WITH_NO_WORKFLOW"),
    
    ERROR("ERROR");

    private String value;

    RepoInformedStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RepoInformedStatusEnum fromValue(String value) {
      for (RepoInformedStatusEnum b : RepoInformedStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REPO_INFORMED_STATUS = "repoInformedStatus";
  private RepoInformedStatusEnum repoInformedStatus;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public RepoDto() {
  }

  public RepoDto accountOwnerUserAccountId(String accountOwnerUserAccountId) {
    
    this.accountOwnerUserAccountId = accountOwnerUserAccountId;
    return this;
  }

   /**
   * Get accountOwnerUserAccountId
   * @return accountOwnerUserAccountId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_OWNER_USER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountOwnerUserAccountId() {
    return accountOwnerUserAccountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_OWNER_USER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountOwnerUserAccountId(String accountOwnerUserAccountId) {
    this.accountOwnerUserAccountId = accountOwnerUserAccountId;
  }


  public RepoDto createdAt(Long createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public RepoDto defaultBranch(String defaultBranch) {
    
    this.defaultBranch = defaultBranch;
    return this;
  }

   /**
   * Get defaultBranch
   * @return defaultBranch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEFAULT_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultBranch() {
    return defaultBranch;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_BRANCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultBranch(String defaultBranch) {
    this.defaultBranch = defaultBranch;
  }


  public RepoDto fullName(String fullName) {
    
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }


  public RepoDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public RepoDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public RepoDto owner(String owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwner() {
    return owner;
  }


  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(String owner) {
    this.owner = owner;
  }


  public RepoDto provider(ProviderEnum provider) {
    
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProviderEnum getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(ProviderEnum provider) {
    this.provider = provider;
  }


  public RepoDto publiclyAccessible(Boolean publiclyAccessible) {
    
    this.publiclyAccessible = publiclyAccessible;
    return this;
  }

   /**
   * Get publiclyAccessible
   * @return publiclyAccessible
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUBLICLY_ACCESSIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPubliclyAccessible() {
    return publiclyAccessible;
  }


  @JsonProperty(JSON_PROPERTY_PUBLICLY_ACCESSIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPubliclyAccessible(Boolean publiclyAccessible) {
    this.publiclyAccessible = publiclyAccessible;
  }


  public RepoDto repoInformedStatus(RepoInformedStatusEnum repoInformedStatus) {
    
    this.repoInformedStatus = repoInformedStatus;
    return this;
  }

   /**
   * Get repoInformedStatus
   * @return repoInformedStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REPO_INFORMED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RepoInformedStatusEnum getRepoInformedStatus() {
    return repoInformedStatus;
  }


  @JsonProperty(JSON_PROPERTY_REPO_INFORMED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepoInformedStatus(RepoInformedStatusEnum repoInformedStatus) {
    this.repoInformedStatus = repoInformedStatus;
  }


  public RepoDto userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepoDto repoDto = (RepoDto) o;
    return Objects.equals(this.accountOwnerUserAccountId, repoDto.accountOwnerUserAccountId) &&
        Objects.equals(this.createdAt, repoDto.createdAt) &&
        Objects.equals(this.defaultBranch, repoDto.defaultBranch) &&
        Objects.equals(this.fullName, repoDto.fullName) &&
        Objects.equals(this.id, repoDto.id) &&
        Objects.equals(this.name, repoDto.name) &&
        Objects.equals(this.owner, repoDto.owner) &&
        Objects.equals(this.provider, repoDto.provider) &&
        Objects.equals(this.publiclyAccessible, repoDto.publiclyAccessible) &&
        Objects.equals(this.repoInformedStatus, repoDto.repoInformedStatus) &&
        Objects.equals(this.userId, repoDto.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountOwnerUserAccountId, createdAt, defaultBranch, fullName, id, name, owner, provider, publiclyAccessible, repoInformedStatus, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepoDto {\n");
    sb.append("    accountOwnerUserAccountId: ").append(toIndentedString(accountOwnerUserAccountId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    defaultBranch: ").append(toIndentedString(defaultBranch)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    publiclyAccessible: ").append(toIndentedString(publiclyAccessible)).append("\n");
    sb.append("    repoInformedStatus: ").append(toIndentedString(repoInformedStatus)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

