/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.runforesight.foresight.sdk.client.WorkflowStepDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WorkflowStepHistoryDto
 */
@JsonPropertyOrder({
  WorkflowStepHistoryDto.JSON_PROPERTY_JOB_NAME,
  WorkflowStepHistoryDto.JSON_PROPERTY_STEP_NAME,
  WorkflowStepHistoryDto.JSON_PROPERTY_STEP_NUMBER,
  WorkflowStepHistoryDto.JSON_PROPERTY_WORKFLOW_STEP_DTO_LIST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-09T10:54:31.162605Z[Etc/UTC]")
public class WorkflowStepHistoryDto {
  public static final String JSON_PROPERTY_JOB_NAME = "jobName";
  private String jobName;

  public static final String JSON_PROPERTY_STEP_NAME = "stepName";
  private String stepName;

  public static final String JSON_PROPERTY_STEP_NUMBER = "stepNumber";
  private String stepNumber;

  public static final String JSON_PROPERTY_WORKFLOW_STEP_DTO_LIST = "workflowStepDtoList";
  private List<WorkflowStepDto> workflowStepDtoList = null;

  public WorkflowStepHistoryDto() {
  }

  public WorkflowStepHistoryDto jobName(String jobName) {
    
    this.jobName = jobName;
    return this;
  }

   /**
   * Get jobName
   * @return jobName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobName() {
    return jobName;
  }


  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobName(String jobName) {
    this.jobName = jobName;
  }


  public WorkflowStepHistoryDto stepName(String stepName) {
    
    this.stepName = stepName;
    return this;
  }

   /**
   * Get stepName
   * @return stepName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STEP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStepName() {
    return stepName;
  }


  @JsonProperty(JSON_PROPERTY_STEP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStepName(String stepName) {
    this.stepName = stepName;
  }


  public WorkflowStepHistoryDto stepNumber(String stepNumber) {
    
    this.stepNumber = stepNumber;
    return this;
  }

   /**
   * Get stepNumber
   * @return stepNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STEP_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStepNumber() {
    return stepNumber;
  }


  @JsonProperty(JSON_PROPERTY_STEP_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStepNumber(String stepNumber) {
    this.stepNumber = stepNumber;
  }


  public WorkflowStepHistoryDto workflowStepDtoList(List<WorkflowStepDto> workflowStepDtoList) {
    
    this.workflowStepDtoList = workflowStepDtoList;
    return this;
  }

  public WorkflowStepHistoryDto addWorkflowStepDtoListItem(WorkflowStepDto workflowStepDtoListItem) {
    if (this.workflowStepDtoList == null) {
      this.workflowStepDtoList = new ArrayList<>();
    }
    this.workflowStepDtoList.add(workflowStepDtoListItem);
    return this;
  }

   /**
   * Get workflowStepDtoList
   * @return workflowStepDtoList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKFLOW_STEP_DTO_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<WorkflowStepDto> getWorkflowStepDtoList() {
    return workflowStepDtoList;
  }


  @JsonProperty(JSON_PROPERTY_WORKFLOW_STEP_DTO_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkflowStepDtoList(List<WorkflowStepDto> workflowStepDtoList) {
    this.workflowStepDtoList = workflowStepDtoList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowStepHistoryDto workflowStepHistoryDto = (WorkflowStepHistoryDto) o;
    return Objects.equals(this.jobName, workflowStepHistoryDto.jobName) &&
        Objects.equals(this.stepName, workflowStepHistoryDto.stepName) &&
        Objects.equals(this.stepNumber, workflowStepHistoryDto.stepNumber) &&
        Objects.equals(this.workflowStepDtoList, workflowStepHistoryDto.workflowStepDtoList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobName, stepName, stepNumber, workflowStepDtoList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowStepHistoryDto {\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    stepName: ").append(toIndentedString(stepName)).append("\n");
    sb.append("    stepNumber: ").append(toIndentedString(stepNumber)).append("\n");
    sb.append("    workflowStepDtoList: ").append(toIndentedString(workflowStepDtoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

