/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.runforesight.foresight.sdk.client.RepoSearchDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WorkflowSearchDto
 */
@JsonPropertyOrder({
  WorkflowSearchDto.JSON_PROPERTY_END_DATE,
  WorkflowSearchDto.JSON_PROPERTY_FILTER_TEXT,
  WorkflowSearchDto.JSON_PROPERTY_REPOS,
  WorkflowSearchDto.JSON_PROPERTY_START_DATE,
  WorkflowSearchDto.JSON_PROPERTY_STATUSES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-31T12:24:20.857460Z[Etc/UTC]")
public class WorkflowSearchDto {
  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private Long endDate;

  public static final String JSON_PROPERTY_FILTER_TEXT = "filterText";
  private String filterText;

  public static final String JSON_PROPERTY_REPOS = "repos";
  private List<RepoSearchDto> repos = null;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  private Long startDate;

  public static final String JSON_PROPERTY_STATUSES = "statuses";
  private List<String> statuses = null;

  public WorkflowSearchDto() {
  }

  public WorkflowSearchDto endDate(Long endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }


  public WorkflowSearchDto filterText(String filterText) {
    
    this.filterText = filterText;
    return this;
  }

   /**
   * Get filterText
   * @return filterText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILTER_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilterText() {
    return filterText;
  }


  @JsonProperty(JSON_PROPERTY_FILTER_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterText(String filterText) {
    this.filterText = filterText;
  }


  public WorkflowSearchDto repos(List<RepoSearchDto> repos) {
    
    this.repos = repos;
    return this;
  }

  public WorkflowSearchDto addReposItem(RepoSearchDto reposItem) {
    if (this.repos == null) {
      this.repos = new ArrayList<>();
    }
    this.repos.add(reposItem);
    return this;
  }

   /**
   * Get repos
   * @return repos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REPOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RepoSearchDto> getRepos() {
    return repos;
  }


  @JsonProperty(JSON_PROPERTY_REPOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepos(List<RepoSearchDto> repos) {
    this.repos = repos;
  }


  public WorkflowSearchDto startDate(Long startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }


  public WorkflowSearchDto statuses(List<String> statuses) {
    
    this.statuses = statuses;
    return this;
  }

  public WorkflowSearchDto addStatusesItem(String statusesItem) {
    if (this.statuses == null) {
      this.statuses = new ArrayList<>();
    }
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * Get statuses
   * @return statuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStatuses() {
    return statuses;
  }


  @JsonProperty(JSON_PROPERTY_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatuses(List<String> statuses) {
    this.statuses = statuses;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowSearchDto workflowSearchDto = (WorkflowSearchDto) o;
    return Objects.equals(this.endDate, workflowSearchDto.endDate) &&
        Objects.equals(this.filterText, workflowSearchDto.filterText) &&
        Objects.equals(this.repos, workflowSearchDto.repos) &&
        Objects.equals(this.startDate, workflowSearchDto.startDate) &&
        Objects.equals(this.statuses, workflowSearchDto.statuses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endDate, filterText, repos, startDate, statuses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowSearchDto {\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    filterText: ").append(toIndentedString(filterText)).append("\n");
    sb.append("    repos: ").append(toIndentedString(repos)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

