/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.runforesight.foresight.sdk.client.RepoDto;
import com.runforesight.foresight.sdk.client.WorkflowDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WorkflowRunSummaryDto
 */
@JsonPropertyOrder({
  WorkflowRunSummaryDto.JSON_PROPERTY_CONCLUSION,
  WorkflowRunSummaryDto.JSON_PROPERTY_CREATED_AT,
  WorkflowRunSummaryDto.JSON_PROPERTY_DURATION,
  WorkflowRunSummaryDto.JSON_PROPERTY_ID,
  WorkflowRunSummaryDto.JSON_PROPERTY_PROVIDER,
  WorkflowRunSummaryDto.JSON_PROPERTY_REPO,
  WorkflowRunSummaryDto.JSON_PROPERTY_REPO_ID,
  WorkflowRunSummaryDto.JSON_PROPERTY_RUN_ID,
  WorkflowRunSummaryDto.JSON_PROPERTY_STATUS,
  WorkflowRunSummaryDto.JSON_PROPERTY_USER_ACCOUNT_ID,
  WorkflowRunSummaryDto.JSON_PROPERTY_WORKFLOW
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-31T12:24:20.857460Z[Etc/UTC]")
public class WorkflowRunSummaryDto {
  /**
   * Gets or Sets conclusion
   */
  public enum ConclusionEnum {
    ACTION_REQUIRED("ACTION_REQUIRED"),
    
    CANCELLED("CANCELLED"),
    
    FAILURE("FAILURE"),
    
    NEUTRAL("NEUTRAL"),
    
    SUCCESS("SUCCESS"),
    
    SKIPPED("SKIPPED"),
    
    STALE("STALE"),
    
    TIMED_OUT("TIMED_OUT"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    ConclusionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ConclusionEnum fromValue(String value) {
      for (ConclusionEnum b : ConclusionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONCLUSION = "conclusion";
  private ConclusionEnum conclusion;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private Long createdAt;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Long duration;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  /**
   * Gets or Sets provider
   */
  public enum ProviderEnum {
    GITHUB("GITHUB");

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  private ProviderEnum provider;

  public static final String JSON_PROPERTY_REPO = "repo";
  private RepoDto repo;

  public static final String JSON_PROPERTY_REPO_ID = "repoId";
  private String repoId;

  public static final String JSON_PROPERTY_RUN_ID = "runId";
  private String runId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    QUEUED("QUEUED"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    COMPLETED("COMPLETED"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_USER_ACCOUNT_ID = "userAccountId";
  private String userAccountId;

  public static final String JSON_PROPERTY_WORKFLOW = "workflow";
  private WorkflowDto workflow;

  public WorkflowRunSummaryDto() {
  }

  public WorkflowRunSummaryDto conclusion(ConclusionEnum conclusion) {
    
    this.conclusion = conclusion;
    return this;
  }

   /**
   * Get conclusion
   * @return conclusion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONCLUSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConclusionEnum getConclusion() {
    return conclusion;
  }


  @JsonProperty(JSON_PROPERTY_CONCLUSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConclusion(ConclusionEnum conclusion) {
    this.conclusion = conclusion;
  }


  public WorkflowRunSummaryDto createdAt(Long createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public WorkflowRunSummaryDto duration(Long duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(Long duration) {
    this.duration = duration;
  }


  public WorkflowRunSummaryDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public WorkflowRunSummaryDto provider(ProviderEnum provider) {
    
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProviderEnum getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(ProviderEnum provider) {
    this.provider = provider;
  }


  public WorkflowRunSummaryDto repo(RepoDto repo) {
    
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REPO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RepoDto getRepo() {
    return repo;
  }


  @JsonProperty(JSON_PROPERTY_REPO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepo(RepoDto repo) {
    this.repo = repo;
  }


  public WorkflowRunSummaryDto repoId(String repoId) {
    
    this.repoId = repoId;
    return this;
  }

   /**
   * Get repoId
   * @return repoId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REPO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRepoId() {
    return repoId;
  }


  @JsonProperty(JSON_PROPERTY_REPO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepoId(String repoId) {
    this.repoId = repoId;
  }


  public WorkflowRunSummaryDto runId(String runId) {
    
    this.runId = runId;
    return this;
  }

   /**
   * Get runId
   * @return runId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRunId() {
    return runId;
  }


  @JsonProperty(JSON_PROPERTY_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRunId(String runId) {
    this.runId = runId;
  }


  public WorkflowRunSummaryDto status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public WorkflowRunSummaryDto userAccountId(String userAccountId) {
    
    this.userAccountId = userAccountId;
    return this;
  }

   /**
   * Get userAccountId
   * @return userAccountId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserAccountId() {
    return userAccountId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAccountId(String userAccountId) {
    this.userAccountId = userAccountId;
  }


  public WorkflowRunSummaryDto workflow(WorkflowDto workflow) {
    
    this.workflow = workflow;
    return this;
  }

   /**
   * Get workflow
   * @return workflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKFLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WorkflowDto getWorkflow() {
    return workflow;
  }


  @JsonProperty(JSON_PROPERTY_WORKFLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkflow(WorkflowDto workflow) {
    this.workflow = workflow;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowRunSummaryDto workflowRunSummaryDto = (WorkflowRunSummaryDto) o;
    return Objects.equals(this.conclusion, workflowRunSummaryDto.conclusion) &&
        Objects.equals(this.createdAt, workflowRunSummaryDto.createdAt) &&
        Objects.equals(this.duration, workflowRunSummaryDto.duration) &&
        Objects.equals(this.id, workflowRunSummaryDto.id) &&
        Objects.equals(this.provider, workflowRunSummaryDto.provider) &&
        Objects.equals(this.repo, workflowRunSummaryDto.repo) &&
        Objects.equals(this.repoId, workflowRunSummaryDto.repoId) &&
        Objects.equals(this.runId, workflowRunSummaryDto.runId) &&
        Objects.equals(this.status, workflowRunSummaryDto.status) &&
        Objects.equals(this.userAccountId, workflowRunSummaryDto.userAccountId) &&
        Objects.equals(this.workflow, workflowRunSummaryDto.workflow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conclusion, createdAt, duration, id, provider, repo, repoId, runId, status, userAccountId, workflow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowRunSummaryDto {\n");
    sb.append("    conclusion: ").append(toIndentedString(conclusion)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    repoId: ").append(toIndentedString(repoId)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userAccountId: ").append(toIndentedString(userAccountId)).append("\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

