/*
 * Foresight Private REST API
 * \"Foresight Private REST API for clients\"
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@runforesight.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.runforesight.foresight.sdk.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WorkflowTelemetryRequest
 */
@JsonPropertyOrder({
  WorkflowTelemetryRequest.JSON_PROPERTY_META_DATA,
  WorkflowTelemetryRequest.JSON_PROPERTY_TELEMETRY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-09T13:11:04.618466Z[Etc/UTC]")
public class WorkflowTelemetryRequest {
  public static final String JSON_PROPERTY_META_DATA = "metaData";
  private Object metaData;

  public static final String JSON_PROPERTY_TELEMETRY_DATA = "telemetryData";
  private Object telemetryData;

  public WorkflowTelemetryRequest() {
  }

  public WorkflowTelemetryRequest metaData(Object metaData) {
    
    this.metaData = metaData;
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_META_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetaData() {
    return metaData;
  }


  @JsonProperty(JSON_PROPERTY_META_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaData(Object metaData) {
    this.metaData = metaData;
  }


  public WorkflowTelemetryRequest telemetryData(Object telemetryData) {
    
    this.telemetryData = telemetryData;
    return this;
  }

   /**
   * Get telemetryData
   * @return telemetryData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TELEMETRY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getTelemetryData() {
    return telemetryData;
  }


  @JsonProperty(JSON_PROPERTY_TELEMETRY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTelemetryData(Object telemetryData) {
    this.telemetryData = telemetryData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowTelemetryRequest workflowTelemetryRequest = (WorkflowTelemetryRequest) o;
    return Objects.equals(this.metaData, workflowTelemetryRequest.metaData) &&
        Objects.equals(this.telemetryData, workflowTelemetryRequest.telemetryData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metaData, telemetryData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowTelemetryRequest {\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    telemetryData: ").append(toIndentedString(telemetryData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

