name: build-java-sdk

on:
  pull_request:
    branches: [master]
    paths:
      - 'java/**'
  workflow_dispatch:

jobs:
  build-java-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install