name: sync-api-java-pr

on:
  workflow_dispatch:
    inputs:
      api_spec_url:
        description: "Api Spec Url"
        required: true
        default: "https://api.service.runforesight.us/v2/api-docs"
  
jobs:
  sync-api-java-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Install openapi-generator-cli
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Create Branch
        run: git checkout -b 'feature/sync-repo-java'
      - name: Get Api Spec
        run: wget ${{ github.event.inputs.api_spec_url }} -O api-spec.json
      - name: Validate Api Spec
        run: openapi-generator-cli validate -i ./api-spec.json
      - name: Clear Old Files
        continue-on-error: true
        run:  rm -R ./src/main/java/com/runforesight/foresight/sdk
      - name: Generate Client
        run: openapi-generator-cli generate -i ./api-spec.json -g java -o ./generated --additional-properties=sourceFolder=src/main/java,library=resteasy,artifactId=foresight-java-client,groupId=com.runforesight,modelPackage=com.runforesight.foresight.sdk.client,apiPackage=com.runforesight.foresight.sdk.client
      - name: Copy Client
        run: cp -r ./generated/src/main/java/com/runforesight/foresight/* ./src/main/java/com/runforesight/foresight
      - name: git status
        run: git status
      - name: git add
        run: git add src/**
      - name: git commit
        run: git commit -m "Repo Sync Java"
      - name: git push
        run: git push origin feature/sync-repo-java
      - name: create pull request
        run: gh pr create -B master -H 'feature/sync-repo-java' --title 'Repo Sync Java' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.FORESIGHT_GITHUB_TOKEN }}